### ISSUE TITLE
`IDNA_NONTRANSITIONAL_TO_ASCII` is not available when using the IDN extension

### ISSUE THREAD

**Issue by dtdesign** [ezyang/htmlpurifier#168]
Some hosts seem to use a IDN PHP-extension that exposes functions like `idn_to_ascii()`, but lack the constant `IDNA_NONTRANSITIONAL_TO_ASCII`, possibly others too. This causes the change in ce0ede2 to fail on these hosts, because there is no check for the existence of the constant itself.

I've found some similar issues in other projects that suggest that this is more wide-spread than one would assume. From what I know at least one larger German hosting company is affected by this.
* https://git.ispconfig.org/ispconfig/ispconfig3/issues/4237
* https://stackoverflow.com/questions/17360179/idn-to-ascii-not-working-in-php-5-4-16-centos6

You can search by the name of the constant to dig up more cases of this.

**Comment by benjaminkohl** [comment]
I am currently being affected by this issue and I see there is a defined() check in place on master now but it hasn't made its way into a release yet. Is that correct? Our project's lock file shows this package at v4.10.0.

**Comment by bytestream** [comment]
@ezyang unless I'm mistaken, the constants defined in https://github.com/ezyang/htmlpurifier/pull/148 are only available if you have php-intl installed: https://github.com/php/php-src/search?q=IDNA_NONTRANSITIONAL_TO_ASCII & http://php.net/manual/en/intl.constants.php so that MR has inadvertently added an unexpected dependency in HTML Purifier v4.10.0

Please can you push a new release with the above in mind?
