### ISSUE TITLE
preFilter method  (& others) non required parameters

### ISSUE THREAD

**Issue by samus-aran** [ezyang/htmlpurifier#182]
Identifying non required parameters within core project which are then enforced into an extended class unnecessarily.
Potentially these could be deem as null to ensure that PHP7 errors don't get flagged up when they are not required to do so when the parameters are more often or not necessary.

https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/Filter.php#L38
https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/Filter.php#L50

This is a placeholder (and reminder to our devs) to associate a PR with it and reference to the issue raised.
https://github.com/salesagility/SuiteCRM/pull/5959

**Comment by xemlock** [comment]
@samus-aran All of these parameters are necessary, because of how `preFilter` logic is executed. `$config` and `$context` parameters are [always provided](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier.php#L202).

It's up to subclass implementation of `preFilter` to decide whether to use these parameters or not. I see no reason for any PHP7 errors to appear here.

IMHO this issue is invalid.
