### ISSUE TITLE
purifying incomplete tag with class="someclass included gives strange result

### ISSUE THREAD

**Issue by githubertus** [ezyang/htmlpurifier#210]
Having just visited your demo page I tried purifying
`<span class="inter`
and got
`<span class="inter&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"></span>`
in return.

Purifying `<span id="inter` and `<span style="inter` returns
`<span></span>`
correctly.

Seems to happen only if CLASS is involved...

**Comment by ezyang** [comment]
This is an artifact of how we do parsing (the parsing API we use requires a full HTML doc so we add some extra tags to set it up). Probably not going to get fixed.

**Comment by githubertus** [comment]
Ok, so I tried a "full" doc like
```
<!doctype html>
<html lang="en">
<body>
<span class="inter
</body>
</html>
```
and the result is still the same.

Aside from that: I wouldn't need a purifier if I can assume the html to be checked is complete/okay.
And again, this only happens to `<span>` if the **class** attribute is involved.

Another example for something's going wrong 
`<img src="xyz`
gives
`<img src="xyz%20" alt="html&gt;" />`

**Comment by ezyang** [comment]
As I said, this is a parsing problem, where the lack of the closing quote causes the parser used by HTML Purifier to read in the rest of the text (leading to the occurrence of the `html` tag you see.) This could be fixed by changing the parser to directly parse without the wrapping html doc, so that it can't hallucinate an extra html tag, but this isn't supported by the parser (dom) that HTML Purifier uses by default.

So, we can fix this by getting another parser, but it's pretty important for performance for the parser to be written in C, and many years ago when I looked at this, there weren't other portable alternatives. Maybe this has changed? But if there hasn't been changed, there isn't any good way to fix this.
