### ISSUE TITLE
How to keep end-of-lines between <img> and other tags, by default?

### ISSUE THREAD

**Issue by Rikk** [ezyang/htmlpurifier#95]
First time using HTML Purifier. It is a great filter!

It took some time until I figured out that setting `Core.CollectErrors` to `true` just prevented Purifier from eating up newlines after `<img>` tags when they are followed by other tags.

I don't know why it removes by default line-breaks after images followed by other tags, why `Core.CollectErrors` fixes it, and if there are other cases where it removes eol magically.

Please, any tip?

Images showing this:

![end-of-lines-demo](https://cloud.githubusercontent.com/assets/2916485/18430528/508e3072-78af-11e6-8fff-5aed4c0d780c.png)

Btw, why doesn't it support HTML5 officially?

**Comment by ezyang** [comment]
This is PHP's dom extension's fault. dom drops whitespace in some situations; we also have a (slower) pure PHP implementation of the lexer which doesn't have this problem. If you set `Core.LexerImpl` to `DirectLex` that will have an equivalent effect.

> Btw, why doesn't it support HTML5 officially?

Because no one has implemented it! A lot of elements to go through and whitelist.

**Comment by Rikk** [comment]
Thanks for the fast answer. I'll try it.
But, as I read "DOMLex (the default PHP5 implementation) and DirectLex (the default PHP4 implementation)". What are the [main] differences? Does the older break something the newer fixed?
In the source (`Lexer.php`) I see a `PH5P` what is it?

**Comment by ezyang** [comment]
I mean, they're different implementations. DirectLex is a lot more precise when it comes to preserving whitespace; in some cases the two will parse HTML differently. DOMLex is default because it's faster (it's implemented in C, opposed to DirectLex in PHP.) PH5P is an experimental parser based off of an old version of the HTML5 spec. Its code was ripped from html5lib.
